# Copyright (c) 2025 Telefonaktiebolaget LM Ericsson
# ScrumMate Image Policy Configuration

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: scrummate-frontend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: scrummate-frontend
  policy:
    semver:
      range: ">=1.0.0"
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
    extract: '$1'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: scrummate-backend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: scrummate-backend
  policy:
    semver:
      range: ">=1.0.0"
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
    extract: '$1'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: scrummate-frontend-dev-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: scrummate-frontend
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^dev-.*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: scrummate-backend-dev-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: scrummate-backend
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^dev-.*'
