# Copyright (c) 2025 Telefonaktiebolaget LM Ericsson
# ScrumMate Cluster Sync Configuration

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/GITHUB_USER/ScrumMate
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/clusters/scrummate-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
