# Copyright (c) 2025 Telefonaktiebolaget LM Ericsson
# ScrumMate - Comprehensive Health Checks Configuration

apiVersion: v1
kind: ConfigMap
metadata:
  name: health-check-config
  namespace: scrummate-prod
data:
  health-check-intervals.yaml: |
    # Health check timing configuration
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    startup:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrummate-backend-health
  namespace: scrummate-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scrummate-backend
  template:
    metadata:
      labels:
        app: scrummate-backend
    spec:
      containers:
      - name: backend
        image: scrummate/backend:latest
        ports:
        - containerPort: 8080
        # Startup probe - allows slow starting containers
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        # Liveness probe - restarts container if unhealthy
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        # Readiness probe - removes from service if not ready
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrummate-frontend-health
  namespace: scrummate-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scrummate-frontend
  template:
    metadata:
      labels:
        app: scrummate-frontend
    spec:
      containers:
      - name: frontend
        image: scrummate/frontend:latest
        ports:
        - containerPort: 80
        # Startup probe for nginx
        startupProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        # Readiness probe
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  namespace: scrummate-prod
spec:
  selector:
    app: health-monitor
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-health-checker
  namespace: scrummate-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-monitor
  template:
    metadata:
      labels:
        app: health-monitor
    spec:
      containers:
      - name: health-monitor
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while true; do
            # Check database connectivity
            if nc -z scrummate-db 5432; then
              echo "$(date): Database health check PASSED"
            else
              echo "$(date): Database health check FAILED"
            fi
            
            # Check backend service
            if curl -f http://scrummate-backend:8080/actuator/health; then
              echo "$(date): Backend health check PASSED"
            else
              echo "$(date): Backend health check FAILED"
            fi
            
            # Check frontend service
            if curl -f http://scrummate-frontend/health; then
              echo "$(date): Frontend health check PASSED"
            else
              echo "$(date): Frontend health check FAILED"
            fi
            
            sleep 30
          done
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
