# Copyright (c) 2025 Telefonaktiebolaget LM Ericsson
# ScrumMate - Production Monitoring Configuration

apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.ericsson.com:587'
      smtp_from: 'scrummate-alerts@ericsson.com'
    
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'
        group_wait: 0s
        repeat_interval: 5m
      - match:
          severity: warning
        receiver: 'warning-alerts'
        repeat_interval: 30m
    
    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://status-page:8080/webhook'
    
    - name: 'critical-alerts'
      email_configs:
      - to: 'oncall-team@ericsson.com'
        subject: 'CRITICAL: ScrumMate Alert - {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Instance: {{ .CommonLabels.instance }}
          Description: {{ .CommonAnnotations.description }}
          Runbook: {{ .CommonAnnotations.runbook_url }}
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#scrummate-critical'
        title: 'CRITICAL Alert: {{ .GroupLabels.alertname }}'
        text: '{{ .CommonAnnotations.description }}'
    
    - name: 'warning-alerts'
      email_configs:
      - to: 'scrummate-team@ericsson.com'
        subject: 'WARNING: ScrumMate Alert - {{ .GroupLabels.alertname }}'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#scrummate-alerts'
        title: 'Warning: {{ .GroupLabels.alertname }}'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  scrummate-rules.yml: |
    groups:
    - name: scrummate.rules
      rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up{job=~"scrummate-.*"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "{{ $labels.job }} service is down"
          runbook_url: "https://wiki.ericsson.com/scrummate/runbooks/service-down"
      
      # High error rate alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          description: "High error rate detected: {{ $value }} errors/sec"
          runbook_url: "https://wiki.ericsson.com/scrummate/runbooks/high-error-rate"
      
      # Response time alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "95th percentile response time is {{ $value }}s"
          runbook_url: "https://wiki.ericsson.com/scrummate/runbooks/high-response-time"
      
      # Database connection alerts
      - alert: DatabaseConnectionHigh
        expr: hikaricp_connections_active / hikaricp_connections_max > 0.8
        for: 3m
        labels:
          severity: warning
        annotations:
          description: "Database connection pool usage is {{ $value | humanizePercentage }}"
      
      # Memory usage alerts
      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Container memory usage is {{ $value | humanizePercentage }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-page
  template:
    metadata:
      labels:
        app: status-page
    spec:
      containers:
      - name: status-page
        image: statuspage/statuspage:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVICES_CONFIG
          value: |
            services:
              - name: "ScrumMate Frontend"
                url: "http://scrummate-frontend/health"
                expected_status: 200
              - name: "ScrumMate Backend"
                url: "http://scrummate-backend:8080/actuator/health"
                expected_status: 200
              - name: "Database"
                url: "tcp://scrummate-db:5432"
                type: "tcp"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: status-page
  namespace: monitoring
spec:
  selector:
    app: status-page
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitoring-health-check
  namespace: monitoring
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-checker
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              # Check all critical services
              SERVICES="scrummate-frontend:80/health scrummate-backend:8080/actuator/health"
              
              for service in $SERVICES; do
                if ! curl -f "http://$service" --max-time 10; then
                  echo "ALERT: Service $service is unhealthy"
                  # Send alert to monitoring system
                  curl -X POST http://alertmanager:9093/api/v1/alerts \
                    -H "Content-Type: application/json" \
                    -d '[{
                      "labels": {
                        "alertname": "ServiceHealthCheck",
                        "service": "'$service'",
                        "severity": "critical"
                      },
                      "annotations": {
                        "description": "Service '$service' failed health check"
                      }
                    }]'
                fi
              done
          restartPolicy: OnFailure

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-production
  namespace: monitoring
data:
  production-dashboard.json: |
    {
      "dashboard": {
        "title": "ScrumMate Production Dashboard",
        "panels": [
          {
            "title": "Service Availability",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=~\"scrummate-.*\"}"
              }
            ]
          },
          {
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total[5m])"
              }
            ]
          },
          {
            "title": "Error Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total{status=~\"5..\"}[5m])"
              }
            ]
          },
          {
            "title": "Response Time (95th percentile)",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))"
              }
            ]
          }
        ]
      }
    }
